.PHONY: clean All

All:
	@echo "----------Building project:[ Q2ClassHierarchy - Debug ]----------"
	@cd "Q2ClassHierarchy" && "$(MAKE)" -f  "Q2ClassHierarchy.mk"
clean:
	@echo "----------Cleaning project:[ Q2ClassHierarchy - Debug ]----------"
	@cd "Q2ClassHierarchy" && "$(MAKE)" -f  "Q2ClassHierarchy.mk" clean
