.PHONY: clean All

All:
	@echo "----------Building project:[ Q1 - Debug ]----------"
	@cd "Q1" && "$(MAKE)" -f  "Q1.mk"
clean:
	@echo "----------Cleaning project:[ Q1 - Debug ]----------"
	@cd "Q1" && "$(MAKE)" -f  "Q1.mk" clean
